name: actions-test
packagePath: .
commitMessageTemplate: 'chore(release): release {{new-version}}'
identifierBase: false
pushTag: true
githubRepo: auto
githubRelease: true
githubReleasePrerelease: true
