name: Automatic Label Sync

on:
  workflow_dispatch:

jobs:
  label_sync:
    uses: sapphiredev/.github/.github/workflows/reusable-labelsync.yml@main
    with:
      operating-system: ubuntu-latest
      merge-labels: true
      repository-overwrite-labels: favna/action-tests
