name: TestPush

on:
  push:
    branches:
      - main

jobs:
  TestPush:
    name: TestPush
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Publish Docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo -e "\n# Initialize some useful variables"
          REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          BRANCH_OR_TAG=`awk -F/ '{print $2}' <<< $GITHUB_REF`
          CURRENT_BRANCH=`awk -F/ '{print $NF}' <<< $GITHUB_REF`

          if [ "$BRANCH_OR_TAG" == "heads" ]; then
            SOURCE_TYPE="branch"
          else
            SOURCE_TYPE="tag"
          fi

          echo -e "\n# Checkout the repo in the target branch"
          TARGET_BRANCH="tempbranch"
          git clone $REPO out -b $TARGET_BRANCH

          echo -e "\n# Commit and push"
          cd out
          touch ${RANDOM}.txt
          git add --all .
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_EMAIL}"
          git commit -m "testing: ${GITHUB_SHA}" || true
          git push origin $TARGET_BRANCH
        env:
          GITHUB_ACTOR: Favware-bot
          GITHUB_EMAIL: favwarebot@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
